import path from 'node:path';

import fs from 'fs-extra';

import { parsePlanContent } from './parser.js';
import type { PlanStatus, PlanSummary } from './types.js';

const PLAN_INDEX_FILE = 'index.md';

export async function collectPlanSummaries(plansDir: string): Promise<PlanSummary[]> {
  const exists = await fs.pathExists(plansDir);
  if (!exists) return [];

  const entries = await fs.readdir(plansDir);
  const planFiles = entries
    .filter((entry) => entry.endsWith('.md'))
    .filter((entry) => entry !== PLAN_INDEX_FILE)
    .sort();

  const summaries: PlanSummary[] = [];

  for (const fileName of planFiles) {
    const fullPath = path.join(plansDir, fileName);
    const content = await fs.readFile(fullPath, 'utf-8');
    const parsed = parsePlanContent(content);

    summaries.push({
      id: parsed.frontmatter.id,
      title: parsed.frontmatter.title,
      status: parsed.frontmatter.status,
      owner: parsed.frontmatter.owner ?? 'unassigned',
      updated: parsed.frontmatter.updated ?? 'n/a',
      phase: parsed.frontmatter.phase ?? 'n/a',
      fileName,
    });
  }

  return summaries;
}

export async function rebuildPlansIndex(plansDir: string): Promise<void> {
  await fs.ensureDir(plansDir);
  const summaries = await collectPlanSummaries(plansDir);

  const active = summaries.filter((p) => p.status === 'in_progress');
  const approved = summaries.filter((p) => p.status === 'approved');
  const draft = summaries.filter((p) => p.status === 'draft');
  const blocked = summaries.filter((p) => p.status === 'blocked');
  const done = summaries.filter((p) => p.status === 'done');
  const abandoned = summaries.filter((p) => p.status === 'abandoned');

  const content = [
    '---',
    'nexus_doc: true',
    'id: "plans_index"',
    'title: "NEXUS Plans Dashboard"',
    'status: auto',
    `generated_at: "${new Date().toISOString().split('T')[0] ?? ''}"`,
    '---',
    '',
    '# Plans Dashboard',
    '',
    '> Auto-generated by `nexus plan` commands. Do not edit by hand.',
    '',
    ...renderStatusTable('Active', active),
    ...renderStatusTable('Approved', approved),
    ...renderStatusTable('Draft', draft),
    ...renderStatusTable('Blocked', blocked),
    ...renderStatusTable('Done', done),
    ...renderStatusTable('Abandoned', abandoned),
    '',
    '## Legend',
    '',
    '| Status | Meaning |',
    '|--------|---------|',
    '| 📝 draft | Created, not yet reviewed/approved |',
    '| 📋 approved | Reviewed, ready to start |',
    '| 🟢 in_progress | Actively being worked |',
    '| ⏸ blocked | Waiting on dependency or decision |',
    '| ✅ done | Completed and verified |',
    '| 🚫 abandoned | Dropped, kept for history |',
    '',
  ].join('\n');

  await fs.writeFile(path.join(plansDir, PLAN_INDEX_FILE), content, 'utf-8');
}

function renderStatusTable(title: string, plans: PlanSummary[]): string[] {
  const rows = plans
    .sort((a, b) => b.updated.localeCompare(a.updated))
    .map((plan) => {
      const icon = statusIcon(plan.status);
      return `| [\`${plan.id}\`](./${plan.fileName}) | ${plan.title} | ${icon} ${plan.status} | ${plan.owner} | ${plan.updated} | ${plan.phase} |`;
    });

  return [
    `## ${title}`,
    '',
    '| ID | Title | Status | Owner | Updated | Phase |',
    '|----|-------|--------|-------|---------|-------|',
    ...(rows.length > 0 ? rows : ['| — | (none) | — | — | — | — |']),
    '',
  ];
}

function statusIcon(status: PlanStatus): string {
  const icons: Record<PlanStatus, string> = {
    draft: '📝',
    approved: '📋',
    in_progress: '🟢',
    blocked: '⏸',
    done: '✅',
    abandoned: '🚫',
  };

  return icons[status];
}
