/**
 * NEXUS CLI - AI Config Generator
 *
 * Generates AI agent instruction files for every major coding assistant.
 *
 * Strategy:
 *   All real content lives in `.nexus/ai/` — a single folder that beginners
 *   can understand ("this is for AI tools") without cluttering the repo root.
 *
 *   Thin pointer files are placed at the paths each tool expects:
 *     .cursorrules           → reads .nexus/ai/instructions.md
 *     .windsurfrules         → reads .nexus/ai/instructions.md
 *     .clinerules            → reads .nexus/ai/instructions.md
 *     AGENTS.md              → reads .nexus/ai/instructions.md
 *     .github/copilot-instructions.md → full content (Copilot requires this path)
 *
 *   Every file is project-aware — it references the actual framework, data
 *   strategy, test framework, and patterns chosen during `nexus init`.
 */

import type { NexusConfig } from '../types/config.js';
import type { GeneratedFile } from '../types/templates.js';
import { version } from '../version.js';

/* ──────────────────────────────────────────────────────────────
 * Public API
 * ────────────────────────────────────────────────────────────── */

/**
 * Generate all AI agent configuration files for the project.
 */
export function generateAiConfig(config: NexusConfig): GeneratedFile[] {
  const files: GeneratedFile[] = [];

  // Core instruction file (the single source of truth)
  files.push(generateInstructions(config));

  // Tool-specific pointer files at expected root paths
  files.push(generateCursorRules());
  files.push(generateWindsurfRules());
  files.push(generateClineRules());
  files.push(generateAgentsMd());
  files.push(generateCopilotInstructions(config));

  return files;
}

/* ──────────────────────────────────────────────────────────────
 * Core instructions file (.nexus/ai/instructions.md)
 * ────────────────────────────────────────────────────────────── */

function generateInstructions(config: NexusConfig): GeneratedFile {
  const frameworkDisplay = getFrameworkDisplay(config.frontendFramework);
  const testDisplay = config.testFramework === 'none' ? 'None configured' : config.testFramework;
  const patternsDisplay =
    config.appPatterns.length > 0 ? config.appPatterns.join(', ') : 'None selected';
  const backendDisplay =
    config.backendFramework === 'none'
      ? `${config.backendStrategy} (no framework)`
      : `${config.backendFramework} (${config.backendStrategy})`;

  const content = `# ${config.projectName} — AI Agent Instructions

> **This file is the single source of truth for all AI coding assistants.**
> It is auto-generated by [NEXUS CLI](https://github.com/GDA-Africa/nexus-cli) v${version}.
> Root-level config files (.cursorrules, .windsurfrules, etc.) point here.

---

## ⚠️ Before You Do Anything

**Read \`.nexus/docs/01_vision.md\` first** to understand what this project does.
Then read \`.nexus/docs/07_implementation.md\` for the build plan and file-by-file guide.

The full doc map is in \`.nexus/index.md\`.

---

## Project Identity

| Field | Value |
|-------|-------|
| **Name** | ${config.projectName} |
| **Type** | ${config.projectType} |
| **Framework** | ${frameworkDisplay} |
| **Data Strategy** | ${config.dataStrategy} |
| **Backend** | ${backendDisplay} |
| **Testing** | ${testDisplay} |
| **Package Manager** | ${config.packageManager} |
| **Generated With** | NEXUS CLI v${version} |

---

## Tech Stack

| Component | Technology |
|-----------|-----------|
| Frontend | ${frameworkDisplay} |
| Language | TypeScript (strict mode, ESM) |
| Data Strategy | ${config.dataStrategy} |
| Backend | ${backendDisplay} |
| Testing | ${testDisplay} |
| Package Manager | ${config.packageManager} |
| Patterns | ${patternsDisplay} |

---

## Code Rules

1. **TypeScript strict mode** — no \`any\`, no implicit returns, no unused variables
2. **ESM only** — use \`import\`/\`export\`, never \`require()\`
3. **File extensions in imports** — always use \`.js\` extension (e.g., \`import { foo } from './bar.js'\`)
4. **Conventional Commits** — \`feat:\`, \`fix:\`, \`docs:\`, \`chore:\`, \`test:\`, \`refactor:\`
5. **Test everything** — every feature needs tests in \`tests/unit/\`
6. **Validate after changes** — run \`${getValidationCommand(config)}\`

---

## Architecture Rules

- Follow the patterns described in \`.nexus/docs/02_architecture.md\`
- Data models must match contracts in \`.nexus/docs/03_data_contracts.md\`
- API endpoints must match contracts in \`.nexus/docs/04_api_contracts.md\`
- Business logic rules are in \`.nexus/docs/05_business_logic.md\`
- Build order is defined in \`.nexus/docs/07_implementation.md\`

---

## Key Directories

| Directory | Purpose |
|-----------|---------|
| \`src/\` | Application source code |
| \`tests/\` | Unit, integration, and E2E tests |
| \`.nexus/docs/\` | NEXUS documentation system (8 files) |
| \`.nexus/\` | Project metadata, AI config, and manifest |
| \`public/\` | Static assets |
| \`.github/\` | CI/CD workflows, PR templates |

---

## NEXUS Documentation System

This project includes 8 structured documentation files designed for both humans and AI:

| # | File | Purpose |
|---|------|---------|
| 1 | \`.nexus/docs/01_vision.md\` | Product requirements, user stories, success metrics |
| 2 | \`.nexus/docs/02_architecture.md\` | System design, tech stack decisions, data flow |
| 3 | \`.nexus/docs/03_data_contracts.md\` | Database schemas, validation rules, relationships |
| 4 | \`.nexus/docs/04_api_contracts.md\` | Endpoints, request/response interfaces, status codes |
| 5 | \`.nexus/docs/05_business_logic.md\` | Rules, algorithms, state machines, decision flows |
| 6 | \`.nexus/docs/06_test_strategy.md\` | Coverage targets, test types, testing philosophy |
| 7 | \`.nexus/docs/07_implementation.md\` | Build order, file-by-file implementation plan |
| 8 | \`.nexus/docs/08_deployment.md\` | Infrastructure, CI/CD, environment configuration |

**Start with \`.nexus/docs/01_vision.md\`**, then follow the numbered order.

---

## Workflow

When implementing a feature:

1. **Read the relevant doc** — find the spec in \`.nexus/docs/\`
2. **Check the implementation plan** — \`.nexus/docs/07_implementation.md\`
3. **Write the code** following the architecture in \`.nexus/docs/02_architecture.md\`
4. **Write tests** — match the strategy in \`.nexus/docs/06_test_strategy.md\`
5. **Validate** — \`${getValidationCommand(config)}\`
6. **Commit** — use conventional commits (\`feat:\`, \`fix:\`, etc.)

---

*Generated by [NEXUS CLI](https://github.com/GDA-Africa/nexus-cli) v${version} — AI-native project scaffolding by [GDA Africa](https://github.com/GDA-Africa)*
`;

  return { path: '.nexus/ai/instructions.md', content };
}

/* ──────────────────────────────────────────────────────────────
 * Root pointer files — one line pointing to .nexus/ai/
 *
 * Some tools (Cursor, Windsurf, Cline) read plaintext from
 * their config file and inject it. So we include a brief header
 * plus a "read the real file" directive that the AI will follow.
 * ────────────────────────────────────────────────────────────── */

function pointerContent(toolName: string): string {
  return `# AI Instructions for this project

> **${toolName}:** The full AI agent instructions for this project live in
> \`.nexus/ai/instructions.md\`. Read that file before doing anything.
>
> This file exists at the root because ${toolName} requires it here.
> All configuration is centralized in the \`.nexus/\` folder to keep
> the repository clean and beginner-friendly.

Read \`.nexus/ai/instructions.md\` for:
- Project identity and tech stack
- Code rules and architecture constraints
- NEXUS documentation system map
- Implementation workflow

Also read \`.nexus/docs/01_vision.md\` to understand what this project does.
`;
}

function generateCursorRules(): GeneratedFile {
  return { path: '.cursorrules', content: pointerContent('Cursor') };
}

function generateWindsurfRules(): GeneratedFile {
  return { path: '.windsurfrules', content: pointerContent('Windsurf') };
}

function generateClineRules(): GeneratedFile {
  return { path: '.clinerules', content: pointerContent('Cline') };
}

function generateAgentsMd(): GeneratedFile {
  return { path: 'AGENTS.md', content: pointerContent('Claude Code / OpenAI Codex') };
}

/* ──────────────────────────────────────────────────────────────
 * GitHub Copilot — requires .github/copilot-instructions.md
 *
 * Copilot doesn't follow "read another file" directives as
 * reliably, so we embed the full project-aware instructions
 * directly in this file.
 * ────────────────────────────────────────────────────────────── */

function generateCopilotInstructions(config: NexusConfig): GeneratedFile {
  const frameworkDisplay = getFrameworkDisplay(config.frontendFramework);
  const testDisplay = config.testFramework === 'none' ? 'None configured' : config.testFramework;
  const patternsDisplay =
    config.appPatterns.length > 0 ? config.appPatterns.join(', ') : 'None selected';

  const content = `# ${config.projectName} — GitHub Copilot Instructions

> Auto-generated by NEXUS CLI v${version}. Full instructions also at \`.nexus/ai/instructions.md\`.

## Project: ${config.projectName}

- **Type:** ${config.projectType}
- **Framework:** ${frameworkDisplay}
- **Data Strategy:** ${config.dataStrategy}
- **Testing:** ${testDisplay}
- **Package Manager:** ${config.packageManager}
- **Patterns:** ${patternsDisplay}

## Read First

1. \`.nexus/docs/01_vision.md\` — what this project does
2. \`.nexus/docs/02_architecture.md\` — how it's built
3. \`.nexus/docs/07_implementation.md\` — build order and file plan
4. \`.nexus/ai/instructions.md\` — full AI agent rules

## Code Rules

- TypeScript strict mode — no \`any\`, no implicit returns
- ESM only — \`import\`/\`export\`, never \`require()\`
- File extensions in imports — always \`.js\`
- Conventional Commits — \`feat:\`, \`fix:\`, \`docs:\`, \`chore:\`
- Test everything — \`tests/unit/\`
- Validate: \`${getValidationCommand(config)}\`
`;

  return { path: '.github/copilot-instructions.md', content };
}

/* ──────────────────────────────────────────────────────────────
 * Helpers
 * ────────────────────────────────────────────────────────────── */

function getFrameworkDisplay(framework: string): string {
  const map: Record<string, string> = {
    nextjs: 'Next.js 15 (App Router)',
    'react-vite': 'React + Vite',
    sveltekit: 'SvelteKit',
    nuxt: 'Nuxt 3',
    astro: 'Astro',
    remix: 'Remix',
  };
  return map[framework] ?? framework;
}

function getValidationCommand(config: NexusConfig): string {
  const pm = config.packageManager;
  const runPrefix = pm === 'npm' ? 'npm run' : pm;
  const testCmd = config.testFramework !== 'none' ? ` && ${runPrefix} test` : '';
  return `npx tsc --noEmit${testCmd} && ${runPrefix} lint`;
}
