/**
 * NEXUS CLI - AI Config Generator
 *
 * Generates AI agent instruction files for every major coding assistant.
 *
 * Strategy:
 *   The master file lives in `.nexus/ai/instructions.md` — a single folder
 *   that beginners can understand ("this is for AI tools").
 *
 *   EVERY tool-specific config file gets the FULL project-aware instructions
 *   embedded directly. We do NOT rely on "go read another file" directives
 *   because AI tools ignore cross-file pointers too often.
 *
 *   Files generated:
 *     .nexus/ai/instructions.md       — master file (full content)
 *     .cursorrules                     — Cursor (full content)
 *     .windsurfrules                   — Windsurf (full content)
 *     .clinerules                      — Cline (full content)
 *     AGENTS.md                        — Claude Code / OpenAI Codex (full content)
 *     .github/copilot-instructions.md  — GitHub Copilot (full content)
 *
 *   Every file is project-aware — it references the actual framework, data
 *   strategy, test framework, and patterns chosen during `nexus init`.
 *   Every file includes the onboarding protocol that tells the AI to
 *   populate template docs BEFORE doing anything the user asks.
 */

import type { NexusConfig } from '../types/config.js';
import type { GeneratedFile } from '../types/templates.js';
import { version } from '../version.js';

/* ──────────────────────────────────────────────────────────────
 * Public API
 * ────────────────────────────────────────────────────────────── */

/**
 * Generate all AI agent configuration files for the project.
 */
export function generateAiConfig(config: NexusConfig): GeneratedFile[] {
  const files: GeneratedFile[] = [];

  // Core instruction file (the single source of truth)
  files.push(generateInstructions(config));

  // Tool-specific files at expected root paths — each embeds full instructions
  files.push(generateCursorRules(config));
  files.push(generateWindsurfRules(config));
  files.push(generateClineRules(config));
  files.push(generateAgentsMd(config));
  files.push(generateCopilotInstructions(config));

  return files;
}

/* ──────────────────────────────────────────────────────────────
 * Core instructions file (.nexus/ai/instructions.md)
 * ────────────────────────────────────────────────────────────── */

function generateInstructions(config: NexusConfig): GeneratedFile {
  const frameworkDisplay = getFrameworkDisplay(config.frontendFramework);
  const testDisplay = config.testFramework === 'none' ? 'None configured' : config.testFramework;
  const patternsDisplay =
    config.appPatterns.length > 0 ? config.appPatterns.join(', ') : 'None selected';
  const backendDisplay =
    config.backendFramework === 'none'
      ? `${config.backendStrategy} (no framework)`
      : `${config.backendFramework} (${config.backendStrategy})`;

  const content = `# ${config.displayName} — AI Agent Instructions

> **This file is the single source of truth for all AI coding assistants.**
> It is auto-generated by [NEXUS CLI](https://github.com/GDA-Africa/nexus-cli) v${version}.
> Root-level config files (.cursorrules, .windsurfrules, etc.) embed these same rules.

---

## 🧠 YOUR BRAIN: \`.nexus/docs/index.md\`

**READ \`.nexus/docs/index.md\` FIRST. EVERY TIME. NO EXCEPTIONS.**

That file is your project brain. It contains:
- **Current Objective** — what you should be working on right now
- **Status Matrix** — what's done, what's in progress, what's blocked
- **Feature Backlog** — the prioritized roadmap of what to build
- **What Has Been Built** — every module, file, and test that exists
- **Progress Log** — session-by-session changelog (your memory)
- **What's Next** — your prioritized TODO list
- **Operating Rules** — the rules you MUST follow

\`\`\`
RULE: Before EVERY task, read .nexus/docs/index.md
RULE: After EVERY task, update .nexus/docs/index.md
RULE: When the user asks "what should we work on?" → check the index
RULE: When you finish a feature → update the index, then suggest the next item
RULE: NEVER ask "what enhancements would you like?" — the index has the answer
\`\`\`

---

## 🚨 CRITICAL — Onboarding Protocol (First-Time Setup)

Each NEXUS doc has YAML frontmatter with a \\\`status\\\` field:
- \\\`template\\\` — the doc is still in its default scaffolded state (has TODO placeholders)
- \\\`populated\\\` — the doc has been filled in by a human or AI agent

\\\`\\\`\\\`
STOP. If ANY .nexus/docs/ file has status: template → you MUST populate it FIRST.
Do NOT skip this step. Do NOT jump straight to the user's request.
This is a hard requirement, not a suggestion.
\\\`\\\`\\\`
\\\`\\\`\\\`

### Steps:

1. **Scan the codebase** — read \\\`package.json\\\`, \\\`tsconfig.json\\\`, source files in \\\`src/\\\`,
   route definitions, data models, and test files to understand the project.

2. **Ask the user about their vision** — what are they building? Who are the users?
   What features do they need? Fill in \\\`01_vision.md\\\` and \\\`05_business_logic.md\\\`.

3. **Auto-fill what you can infer** from the code:
   - \\\`02_architecture.md\\\` — tech stack, directory structure, data flow
   - \\\`03_data_contracts.md\\\` — schemas, types, validation from source code
   - \\\`04_api_contracts.md\\\` — routes, endpoints, request/response shapes
   - \\\`06_test_strategy.md\\\` — existing test setup, coverage, test patterns
   - \\\`08_deployment.md\\\` — CI/CD config, environment variables, deploy targets

4. **Build the implementation plan** (\\\`07_implementation.md\\\`):
   - Turn features from \\\`01_vision.md\\\` into concrete build phases
   - Create a file-by-file plan with every file that needs to be created
   - Set the current phase based on what already exists
   - This is HOW you know what code to write

5. **Update the frontmatter** of each doc you fill in:
   \\\`\\\`\\\`yaml
   status: populated
   confidence: high    # or medium/low
   last_updated: "YYYY-MM-DD"
   \\\`\\\`\\\`

6. **Build the project brain** (\\\`.nexus/docs/index.md\\\`):
   - Fill in the feature backlog from \\\`01_vision.md\\\` features
   - Update the status matrix to reflect what's populated
   - Update "What Has Been Built" to reflect current state
   - Set "What's Next" to the first real feature from the backlog
   - **This step is CRITICAL — this file drives all future work**

7. **THEN proceed** with the user's original request — or suggest
   the first item from "What's Next" in the index.

This onboarding flow only applies when docs have \\\`status: template\\\`.
Once all docs are \\\`populated\\\`, skip this section and work normally —
but ALWAYS read \\\`.nexus/docs/index.md\\\` before every task.

---

## Project Identity

| Field | Value |
|-------|-------|
| **Name** | ${config.displayName} |
| **Type** | ${config.projectType} |
| **Framework** | ${frameworkDisplay} |
| **Data Strategy** | ${config.dataStrategy} |
| **Backend** | ${backendDisplay} |
| **Testing** | ${testDisplay} |
| **Package Manager** | ${config.packageManager} |
| **Generated With** | NEXUS CLI v${version} |

---

## Tech Stack

| Component | Technology |
|-----------|-----------|
| Frontend | ${frameworkDisplay} |
| Language | TypeScript (strict mode, ESM) |
| Data Strategy | ${config.dataStrategy} |
| Backend | ${backendDisplay} |
| Testing | ${testDisplay} |
| Package Manager | ${config.packageManager} |
| Patterns | ${patternsDisplay} |

---

## Code Rules

1. **TypeScript strict mode** — no \`any\`, no implicit returns, no unused variables
2. **ESM only** — use \`import\`/\`export\`, never \`require()\`
3. **File extensions in imports** — always use \`.js\` extension (e.g., \`import { foo } from './bar.js'\`)
4. **Conventional Commits** — \`feat:\`, \`fix:\`, \`docs:\`, \`chore:\`, \`test:\`, \`refactor:\`
5. **Test everything** — every feature needs tests in \`tests/unit/\`
6. **Validate after changes** — run \`${getValidationCommand(config)}\`

---

## Architecture Rules

- Follow the patterns described in \`.nexus/docs/02_architecture.md\`
- Data models must match contracts in \`.nexus/docs/03_data_contracts.md\`
- API endpoints must match contracts in \`.nexus/docs/04_api_contracts.md\`
- Business logic rules are in \`.nexus/docs/05_business_logic.md\`
- Build order is defined in \`.nexus/docs/07_implementation.md\`

---

## Key Directories

| Directory | Purpose |
|-----------|---------|
| \`src/\` | Application source code |
| \`tests/\` | Unit, integration, and E2E tests |
| \`.nexus/docs/\` | NEXUS documentation system (8 files) |
| \`.nexus/\` | Project metadata, AI config, and manifest |
| \`public/\` | Static assets |
| \`.github/\` | CI/CD workflows, PR templates |

---

## NEXUS Documentation System

This project includes 8 structured documentation files designed for both humans and AI:

| # | File | Purpose |
|---|------|---------|
| 1 | \`.nexus/docs/01_vision.md\` | Product requirements, user stories, success metrics |
| 2 | \`.nexus/docs/02_architecture.md\` | System design, tech stack decisions, data flow |
| 3 | \`.nexus/docs/03_data_contracts.md\` | Database schemas, validation rules, relationships |
| 4 | \`.nexus/docs/04_api_contracts.md\` | Endpoints, request/response interfaces, status codes |
| 5 | \`.nexus/docs/05_business_logic.md\` | Rules, algorithms, state machines, decision flows |
| 6 | \`.nexus/docs/06_test_strategy.md\` | Coverage targets, test types, testing philosophy |
| 7 | \`.nexus/docs/07_implementation.md\` | Build order, file-by-file implementation plan |
| 8 | \`.nexus/docs/08_deployment.md\` | Infrastructure, CI/CD, environment configuration |
| 🧠 | \`.nexus/docs/index.md\` | **PROJECT BRAIN** — status, backlog, progress, what's next |
| 📚 | \`.nexus/docs/knowledge.md\` | **KNOWLEDGE BASE** — learned insights, patterns, gotchas |

**Start with \`.nexus/docs/index.md\`** (your brain), then \`.nexus/docs/01_vision.md\`.

---

## Workflow — How To Work On This Project

### Before EVERY task:
1. **Read \`.nexus/docs/index.md\`** — check "Current Objective" and "What's Next"
2. **Read the relevant spec doc** — find details in the numbered \`.nexus/docs/\` files
3. **Scan \`.nexus/docs/knowledge.md\`** — check for relevant past learnings before making decisions
4. **Check \`.nexus/docs/07_implementation.md\`** — find the file-by-file plan

### During the task:
4. **Write the code** following the architecture in \`.nexus/docs/02_architecture.md\`
5. **Write tests** — match the strategy in \`.nexus/docs/06_test_strategy.md\`
6. **Validate** — \`${getValidationCommand(config)}\`

### After EVERY task:
7. **Update \`.nexus/docs/index.md\`**:
   - Move completed items from "What's Next" to "Progress Log"
   - Update the "Status Matrix" and "What Has Been Built"
   - Set the "Current Objective" to the next priority item
8. **Update \`.nexus/docs/07_implementation.md\`** — mark completed files/tasks
9. **Learn** — if you discovered something non-obvious (bug pattern, architecture insight, package quirk, performance fix), append an entry to \`.nexus/docs/knowledge.md\`
10. **Commit** — use conventional commits (\`feat:\`, \`fix:\`, etc.)
11. **Suggest the next task** from \`.nexus/docs/index.md\` "What's Next"

### NEVER do this:
- ❌ Ask "what enhancements would you like?" when the backlog has items
- ❌ Invent random features not in the backlog
- ❌ Skip updating the index after completing work
- ❌ Treat docs as static — they evolve with the project

---

*Generated by [NEXUS CLI](https://github.com/GDA-Africa/nexus-cli) v${version} — AI-native project scaffolding by [GDA Africa](https://github.com/GDA-Africa)*
`;

  return { path: '.nexus/ai/instructions.md', content };
}

/* ──────────────────────────────────────────────────────────────
 * Tool-specific instruction files
 *
 * Every AI tool gets the FULL project-aware instructions embedded
 * directly in its config file. We do NOT rely on "go read another
 * file" directives — AI tools ignore them too often.
 *
 * A shared helper generates the content; each tool function just
 * sets the correct output path and tool-specific header.
 * ────────────────────────────────────────────────────────────── */

/**
 * Generate full project-aware instruction content for any AI tool.
 * This is embedded directly in each tool's config file so the AI
 * never has to follow a cross-file pointer.
 */
function toolInstructionContent(config: NexusConfig, toolName: string): string {
  const frameworkDisplay = getFrameworkDisplay(config.frontendFramework);
  const testDisplay = config.testFramework === 'none' ? 'None configured' : config.testFramework;
  const patternsDisplay =
    config.appPatterns.length > 0 ? config.appPatterns.join(', ') : 'None selected';

  return `# ${config.displayName} — ${toolName} Instructions

> Auto-generated by [NEXUS CLI](https://github.com/GDA-Africa/nexus-cli) v${version}.

## 🧠 YOUR BRAIN: \`.nexus/docs/index.md\`

**Read it FIRST. Every time. No exceptions.**

It contains: current objective, feature backlog, progress log, what's next.

\`\`\`
RULE: Before EVERY task → read .nexus/docs/index.md
RULE: After EVERY task → update .nexus/docs/index.md
RULE: NEVER ask "what enhancements would you like?" → the index has the answer
RULE: NEVER invent features → work from the feature backlog
\`\`\`

## 🚨 First-Time Onboarding

If ANY \`.nexus/docs/\` file has \`status: template\` in its YAML frontmatter:

**STOP. Populate the docs BEFORE doing anything else.**
Read \`.nexus/ai/instructions.md\` for the full onboarding steps.

## Project

| Field | Value |
|-------|-------|
| Name | ${config.displayName} |
| Type | ${config.projectType} |
| Framework | ${frameworkDisplay} |
| Data | ${config.dataStrategy} |
| Testing | ${testDisplay} |
| Package Manager | ${config.packageManager} |
| Patterns | ${patternsDisplay} |

## Workflow

1. **Before:** Read \`.nexus/docs/index.md\` → check "What's Next". Scan \`.nexus/docs/knowledge.md\` for relevant past learnings
2. **During:** Write code + tests, validate with \`${getValidationCommand(config)}\`
3. **After:** Update \`.nexus/docs/index.md\` → move item to Progress Log. If you learned something non-obvious, append to \`.nexus/docs/knowledge.md\`
4. **Suggest:** The next item from the backlog

## Code Rules

- TypeScript strict mode — no \`any\`, no implicit returns
- ESM only — \`import\`/\`export\`, never \`require()\`
- Conventional Commits — \`feat:\`, \`fix:\`, \`docs:\`, \`chore:\`
- Test everything — validate: \`${getValidationCommand(config)}\`

## Docs

| File | Purpose |
|------|---------|
| \`.nexus/docs/index.md\` | **🧠 Project brain** — status, backlog, what's next |
| \`.nexus/ai/instructions.md\` | Full AI rules, onboarding protocol, architecture |
| \`.nexus/docs/knowledge.md\` | **📚 Knowledge base** — learned insights, patterns, gotchas |
| \`.nexus/docs/01_vision.md\` | Vision, features, personas |
| \`.nexus/docs/07_implementation.md\` | Build order, file-by-file plan |
`;
}

function generateCursorRules(config: NexusConfig): GeneratedFile {
  return { path: '.cursorrules', content: toolInstructionContent(config, 'Cursor') };
}

function generateWindsurfRules(config: NexusConfig): GeneratedFile {
  return { path: '.windsurfrules', content: toolInstructionContent(config, 'Windsurf') };
}

function generateClineRules(config: NexusConfig): GeneratedFile {
  return { path: '.clinerules', content: toolInstructionContent(config, 'Cline') };
}

function generateAgentsMd(config: NexusConfig): GeneratedFile {
  return { path: 'AGENTS.md', content: toolInstructionContent(config, 'Claude Code / OpenAI Codex') };
}

/* ──────────────────────────────────────────────────────────────
 * GitHub Copilot — requires .github/copilot-instructions.md
 *
 * Uses the same shared content as all other tools.
 * ────────────────────────────────────────────────────────────── */

function generateCopilotInstructions(config: NexusConfig): GeneratedFile {
  return { path: '.github/copilot-instructions.md', content: toolInstructionContent(config, 'GitHub Copilot') };
}

/* ──────────────────────────────────────────────────────────────
 * Helpers
 * ────────────────────────────────────────────────────────────── */

function getFrameworkDisplay(framework: string): string {
  const map: Record<string, string> = {
    nextjs: 'Next.js 15 (App Router)',
    'react-vite': 'React + Vite',
    sveltekit: 'SvelteKit',
    nuxt: 'Nuxt 3',
    astro: 'Astro',
    remix: 'Remix',
  };
  return map[framework] ?? framework;
}

function getValidationCommand(config: NexusConfig): string {
  const pm = config.packageManager;
  const runPrefix = pm === 'npm' ? 'npm run' : pm;
  const testCmd = config.testFramework !== 'none' ? ` && ${runPrefix} test` : '';
  return `npx tsc --noEmit${testCmd} && ${runPrefix} lint`;
}
