/**
 * NEXUS CLI - Skills Generator
 *
 * Generates the `.nexus/skills/` directory structure for a project.
 *
 * What it creates:
 *   .nexus/skills/README.md          — agent-readable index of all installed skills
 *   .nexus/skills/core/<skill>.md    — framework-matched skill files (replaceable on upgrade)
 *   .nexus/skills/custom/README.md   — placeholder with instructions for user-created skills
 *
 * Rules:
 *   - core/     is owned by NEXUS — regenerated on upgrade
 *   - custom/   is owned by the user — NEVER touched by NEXUS (only created once)
 *   - community/ is created empty — populated by `nexus skill install`
 *
 * Skill content is bundled inline until @nexus-framework/skills is published.
 * Once the registry package exists, this generator sources content from it.
 */

import type { NexusConfig } from '../types/config.js';
import type { GeneratedFile } from '../types/templates.js';

/* ──────────────────────────────────────────────────────────────
 * Public API
 * ────────────────────────────────────────────────────────────── */

/**
 * Generate all `.nexus/skills/` files for the project.
 *
 * Returns an empty array if `config.enableSkills` is explicitly false.
 * Defaults to generating skills when enableSkills is undefined (opt-in by default).
 */
export function generateSkills(config: NexusConfig): GeneratedFile[] {
  if (config.enableSkills === false) return [];

  const framework = config.frontendFramework;
  const files: GeneratedFile[] = [];
  const coreSkills = getCoreSkills(framework);

  // Core skill files
  for (const skill of coreSkills) {
    files.push({
      path: `.nexus/skills/core/${skill.slug}.md`,
      content: skill.content,
    });
  }

  // Custom skills placeholder (only created — never overwritten)
  files.push(generateCustomReadme());

  // Skills README index (always regenerated — reflects current skill set)
  files.push(generateSkillsReadme(framework, coreSkills));

  return files;
}

/* ──────────────────────────────────────────────────────────────
 * Skills README index (.nexus/skills/README.md)
 * ────────────────────────────────────────────────────────────── */

function generateSkillsReadme(
  framework: NexusConfig['frontendFramework'],
  coreSkills: SkillDefinition[],
): GeneratedFile {
  const frameworkLabel = getFrameworkLabel(framework);

  const coreTable = coreSkills
    .map((s) => `| \`${s.slug}\` | ${s.triggers.join(', ')} | ${s.status} |`)
    .join('\n');

  const content = `# NEXUS Skills Index

> Auto-generated by NEXUS CLI. Do not edit directly — run \`nexus upgrade\` to refresh.
> Add your own skills in \`custom/\` using \`nexus skill new <name>\`.

---

## What Are Skills?

Skills are pre-read instruction files that tell AI agents **how to execute tasks** in this
specific project. Before performing any significant task, the agent checks this directory for
a matching skill and reads it fully before starting.

**Skills live in three directories:**

| Directory | Owner | Updated By |
|-----------|-------|------------|
| \`core/\` | NEXUS | Regenerated by \`nexus upgrade\` |
| \`custom/\` | You | **Never touched by NEXUS** |
| \`community/\` | Registry | \`nexus skill install <pkg>\` |

**Precedence: \`custom/\` overrides \`core/\`, which overrides \`community/\`.**

---

## Core Skills (${frameworkLabel})

| Skill | Triggers | Status |
|-------|----------|--------|
${coreTable}

## Custom Skills

No custom skills yet. Run \`nexus skill new <name>\` to create one.

Custom skills live in \`.nexus/skills/custom/\` and are **never overwritten** by NEXUS.

## Community Skills

No community skills installed. Run \`nexus skill install <pkg>\` to install from the registry.
`;

  return { path: '.nexus/skills/README.md', content };
}

/* ──────────────────────────────────────────────────────────────
 * Custom skills placeholder
 * ────────────────────────────────────────────────────────────── */

function generateCustomReadme(): GeneratedFile {
  const content = `# Custom Skills

This directory is for **your** project-specific skills.

NEXUS will **never** read from, write to, or delete files in this directory.
It is entirely owned by you.

---

## How to Create a Custom Skill

Run:
\`\`\`
nexus skill new <name>
\`\`\`

This will scaffold a new skill file with the correct frontmatter and section structure.

## Skill File Format

Every skill must have YAML frontmatter:

\`\`\`markdown
---
skill: your-skill-slug
version: 1.0.0
framework: shared
category: ui
triggers:
  - "phrase that activates this skill"
  - "another trigger phrase"
author: your-name
status: draft
---

# Skill: Title

## When to Read This
...

## Steps
1. ...

## Patterns We Use
...

## Anti-Patterns — Never Do This
...

## Example
...
\`\`\`

## Status Values

- \`active\` — AI agents must follow this skill
- \`draft\` — Guidance only; not yet enforced
- \`deprecated\` — Outdated; flag for update

---

*Add your skills here. They take precedence over core and community skills.*
`;

  return { path: '.nexus/skills/custom/README.md', content };
}

/* ──────────────────────────────────────────────────────────────
 * Core skill definitions — bundled inline
 * (Will be sourced from @nexus-framework/skills once published)
 * ────────────────────────────────────────────────────────────── */

interface SkillDefinition {
  slug: string;
  triggers: string[];
  status: 'active' | 'draft' | 'deprecated';
  content: string;
}

function getCoreSkills(framework: NexusConfig['frontendFramework']): SkillDefinition[] {
  const shared = getSharedSkills();
  const frameworkSkills = getFrameworkSkills(framework);
  return [...frameworkSkills, ...shared];
}

function getSharedSkills(): SkillDefinition[] {
  return [
    {
      slug: 'git-workflow',
      triggers: ['committing changes', 'creating a branch', 'making a pull request', 'git commit'],
      status: 'active',
      content: buildSkillFile({
        slug: 'git-workflow',
        version: '1.0.0',
        framework: 'shared',
        category: 'workflow',
        triggers: ['committing changes', 'creating a branch', 'making a pull request', 'git commit'],
        author: '@nexus-framework/skills',
        status: 'active',
        title: 'Git Workflow',
        whenToRead: 'Read this skill before committing, branching, or creating pull requests.',
        context:
          'This project uses Conventional Commits. Every commit message must follow the ' +
          '`type: description` format. Branches follow a `type/short-description` convention.',
        steps: [
          'Branch name: `feat/`, `fix/`, `chore/`, `docs/`, `refactor/`, `test/` prefix + short slug',
          'Commit format: `type(scope?): short description` — e.g. `feat(auth): add login form`',
          'Types: `feat` | `fix` | `docs` | `chore` | `test` | `refactor` | `perf` | `style`',
          'Before committing: run `npx tsc --noEmit && yarn test && yarn lint`',
          'PRs: title must also follow Conventional Commits format',
          'After every significant task: update `.nexus/docs/index.md` and append to `knowledge.md` if applicable',
        ],
        patterns: [
          'Small, focused commits — one logical change per commit',
          'Never commit broken code to main/develop',
          'Always update the project brain (`.nexus/docs/index.md`) after completing a feature',
        ],
        antiPatterns: [
          'Do NOT use generic messages like "update stuff" or "fix"',
          'Do NOT commit generated files that should be in .gitignore',
          'Do NOT squash meaningful history — keep the story legible',
        ],
        example: `feat(auth): add JWT refresh token rotation

Implements sliding refresh token window. Old tokens are invalidated on use.
Resolves #42`,
      }),
    },
    {
      slug: 'knowledge-logging',
      triggers: [
        'completing a task',
        'discovering a bug',
        'making an architectural decision',
        'appending to knowledge base',
      ],
      status: 'active',
      content: buildSkillFile({
        slug: 'knowledge-logging',
        version: '1.0.0',
        framework: 'shared',
        category: 'workflow',
        triggers: [
          'completing a task',
          'discovering a bug',
          'making an architectural decision',
          'appending to knowledge base',
        ],
        author: '@nexus-framework/skills',
        status: 'active',
        title: 'Knowledge Base Logging',
        whenToRead:
          'Read this before appending any entry to `.nexus/docs/knowledge.md`.',
        context:
          'The knowledge base is the project\'s long-term memory. It is append-only. ' +
          'Every entry must follow the exact format so future agents can scan headings quickly.',
        steps: [
          'Open `.nexus/docs/knowledge.md`',
          'Scroll to the bottom',
          'Add a new entry using the exact format below',
          'Use the correct category tag',
          'Keep the description to 1-3 sentences',
          'Save — never delete or edit existing entries',
        ],
        patterns: [
          'Format: `## [YYYY-MM-DD] category — title`',
          'Categories: `architecture` | `bug-fix` | `pattern` | `package` | `performance` | `convention` | `gotcha`',
          'Write entries that would help a future agent avoid a mistake or understand a decision',
        ],
        antiPatterns: [
          'Do NOT delete existing entries — the knowledge base is append-only',
          'Do NOT log routine completions — those go in `index.md` Progress Log',
          'Do NOT write essays — 1-3 sentences maximum per entry',
        ],
        example: `## [2026-03-06] gotcha — select() requires choices array, not enum
@inquirer/prompts select() does not accept a TypeScript enum directly.
Pass an explicit choices array with value/name pairs instead.`,
      }),
    },
  ];
}

function getFrameworkSkills(framework: NexusConfig['frontendFramework']): SkillDefinition[] {
  switch (framework) {
    case 'nextjs':
      return getNextjsSkills();
    case 'react-vite':
      return getReactViteSkills();
    case 'sveltekit':
      return getSvelteKitSkills();
    case 'nuxt':
      return getNuxtSkills();
    case 'astro':
      return getAstroSkills();
    case 'remix':
      return getRemixSkills();
    default:
      return [];
  }
}

/* ─── Next.js Skills ─────────────────────────────────────────── */

function getNextjsSkills(): SkillDefinition[] {
  return [
    {
      slug: 'component-creation',
      triggers: [
        'creating a new component',
        'adding a React component',
        'building a UI element',
        'new component',
      ],
      status: 'active',
      content: buildSkillFile({
        slug: 'component-creation',
        version: '1.0.0',
        framework: 'next.js',
        category: 'ui',
        triggers: [
          'creating a new component',
          'adding a React component',
          'building a UI element',
          'new component',
        ],
        author: '@nexus-framework/skills',
        status: 'active',
        title: 'Creating Components (Next.js)',
        whenToRead: 'Read this skill before creating any new React component in this project.',
        context:
          'This project uses Next.js App Router with TypeScript. All components are ' +
          'React Server Components by default. Add "use client" only when client state or ' +
          'browser APIs are needed.',
        steps: [
          'Place the file in `src/components/<ComponentName>.tsx`',
          'Name the file and export using PascalCase',
          'Default to Server Component (no "use client")',
          'Add "use client" only if using: useState, useEffect, event handlers, browser APIs',
          'Define a TypeScript interface for props: `interface Props { ... }`',
          'Export the component as the default export',
          'Co-locate component-specific styles in `<ComponentName>.module.css` if needed',
          'Write a unit test in `tests/unit/<ComponentName>.test.tsx`',
        ],
        patterns: [
          'Server Components for data-fetching and layout',
          'Client Components for interactivity only',
          'Props interface always explicitly typed — no `any`',
          'One component per file',
        ],
        antiPatterns: [
          'Do NOT add "use client" to components that do not need it',
          'Do NOT use default exports for utility functions — named exports only',
          'Do NOT mix server and client logic in the same component',
        ],
        example: `// src/components/UserCard.tsx
interface Props {
  name: string;
  email: string;
}

export default function UserCard({ name, email }: Props) {
  return (
    <div className="user-card">
      <h2>{name}</h2>
      <p>{email}</p>
    </div>
  );
}`,
      }),
    },
    {
      slug: 'routing',
      triggers: [
        'adding a new page',
        'creating a route',
        'new route',
        'adding navigation',
        'file-based routing',
      ],
      status: 'active',
      content: buildSkillFile({
        slug: 'routing',
        version: '1.0.0',
        framework: 'next.js',
        category: 'routing',
        triggers: [
          'adding a new page',
          'creating a route',
          'new route',
          'adding navigation',
          'file-based routing',
        ],
        author: '@nexus-framework/skills',
        status: 'active',
        title: 'Routing (Next.js App Router)',
        whenToRead:
          'Read this skill before adding any new page, route, or layout to the project.',
        context:
          'This project uses the Next.js 15 App Router. Routes are file-system based under `src/app/`. ' +
          'Every route segment is a directory with a `page.tsx` file. Layouts wrap route segments.',
        steps: [
          'Create a directory under `src/app/` for the route segment: `src/app/<route>/`',
          'Add `page.tsx` as the route\'s UI: `export default function Page() { ... }`',
          'Add `layout.tsx` if this segment needs a wrapping layout',
          'Add `loading.tsx` for streaming/suspense UI',
          'Add `error.tsx` for error boundaries (must be a Client Component)',
          'Use `[param]` folder naming for dynamic routes',
          'Use `(group)` folder naming for route groups that don\'t affect the URL',
        ],
        patterns: [
          'Route entry: `export default function <RouteName>Page() { ... }`',
          'Dynamic route: `src/app/users/[id]/page.tsx` → `{ params }: { params: { id: string } }`',
          'Colocation: keep route-specific components in the same route folder',
        ],
        antiPatterns: [
          'Do NOT use `src/pages/` — this project uses App Router, not Pages Router',
          'Do NOT put shared components in `src/app/` — they go in `src/components/`',
          'Do NOT add "use client" to layouts unless necessary',
        ],
        example: `// src/app/dashboard/page.tsx
export default function DashboardPage() {
  return <main><h1>Dashboard</h1></main>;
}

// src/app/users/[id]/page.tsx
export default function UserPage({ params }: { params: { id: string } }) {
  return <main><h1>User {params.id}</h1></main>;
}`,
      }),
    },
    {
      slug: 'api-routes',
      triggers: [
        'creating an API endpoint',
        'adding a route handler',
        'new API route',
        'server-side endpoint',
      ],
      status: 'active',
      content: buildSkillFile({
        slug: 'api-routes',
        version: '1.0.0',
        framework: 'next.js',
        category: 'api',
        triggers: [
          'creating an API endpoint',
          'adding a route handler',
          'new API route',
          'server-side endpoint',
        ],
        author: '@nexus-framework/skills',
        status: 'active',
        title: 'API Routes (Next.js Route Handlers)',
        whenToRead: 'Read this skill before creating any server-side API endpoint.',
        context:
          'This project uses Next.js Route Handlers (App Router) instead of the legacy API Routes. ' +
          'Route handlers live in `src/app/api/<path>/route.ts`.',
        steps: [
          'Create `src/app/api/<resource>/route.ts`',
          'Export named HTTP method functions: `GET`, `POST`, `PUT`, `DELETE`, `PATCH`',
          'Accept `(request: Request)` as the parameter',
          'Return `Response` or `NextResponse` objects',
          'Validate request body before processing — use `request.json()` then validate shape',
          'Return appropriate HTTP status codes',
          'Handle errors with try/catch and return 500 with a message',
        ],
        patterns: [
          'Named exports per HTTP method: `export async function GET(request: Request)`',
          'Use `NextResponse.json()` for JSON responses',
          'Extract and validate params from `request.url` or `params` for dynamic routes',
        ],
        antiPatterns: [
          'Do NOT use `src/pages/api/` — App Router uses `src/app/api/` with `route.ts`',
          'Do NOT return raw objects — always use `Response` or `NextResponse`',
          'Do NOT skip error handling — every handler needs try/catch',
        ],
        example: `// src/app/api/users/route.ts
import { NextResponse } from 'next/server';

export async function GET() {
  const users = await getUsers(); // your data source
  return NextResponse.json(users);
}

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const user = await createUser(body);
    return NextResponse.json(user, { status: 201 });
  } catch (error) {
    return NextResponse.json({ error: 'Failed to create user' }, { status: 500 });
  }
}`,
      }),
    },
    {
      slug: 'testing',
      triggers: [
        'writing a test',
        'adding unit tests',
        'testing a component',
        'test file',
        'vitest',
      ],
      status: 'active',
      content: buildSkillFile({
        slug: 'testing',
        version: '1.0.0',
        framework: 'next.js',
        category: 'testing',
        triggers: [
          'writing a test',
          'adding unit tests',
          'testing a component',
          'test file',
          'vitest',
        ],
        author: '@nexus-framework/skills',
        status: 'active',
        title: 'Testing (Next.js + Vitest)',
        whenToRead: 'Read this skill before writing any test file in this project.',
        context:
          'This project uses Vitest for unit and integration tests. Test files live ' +
          'in `tests/unit/` mirroring the `src/` structure.',
        steps: [
          'Create test file at `tests/unit/<name>.test.ts` (or `.tsx` for components)',
          'Import from Vitest: `import { describe, it, expect, vi } from \'vitest\'`',
          'Group tests with `describe()`; individual assertions with `it()`',
          'For React components: use `@testing-library/react` with `render()` and `screen`',
          'Mock external modules with `vi.mock(\'./path.js\')`',
          'Use `vi.fn()` for spy functions',
          'Run tests: `yarn test` or `yarn test --watch`',
        ],
        patterns: [
          'One test file per source file',
          'Test the public API — not implementation details',
          '`describe` block matches the module/component name',
          '`it` descriptions read like specifications: "should [behaviour] when [condition]"',
        ],
        antiPatterns: [
          'Do NOT test private implementation details — test observable behaviour',
          'Do NOT use `any` in test files — TypeScript strict mode applies',
          'Do NOT skip the `.js` extension on imports in test files (ESM requirement)',
        ],
        example: `// tests/unit/UserCard.test.tsx
import { describe, it, expect } from 'vitest';
import { render, screen } from '@testing-library/react';
import UserCard from '../../src/components/UserCard.js';

describe('UserCard', () => {
  it('should render the user name', () => {
    render(<UserCard name="Alice" email="alice@example.com" />);
    expect(screen.getByText('Alice')).toBeDefined();
  });
});`,
      }),
    },
  ];
}

/* ─── React + Vite Skills ────────────────────────────────────── */

function getReactViteSkills(): SkillDefinition[] {
  return [
    {
      slug: 'component-creation',
      triggers: ['creating a new component', 'adding a React component', 'new component'],
      status: 'active',
      content: buildSkillFile({
        slug: 'component-creation',
        version: '1.0.0',
        framework: 'react-vite',
        category: 'ui',
        triggers: ['creating a new component', 'adding a React component', 'new component'],
        author: '@nexus-framework/skills',
        status: 'active',
        title: 'Creating Components (React + Vite)',
        whenToRead: 'Read this skill before creating any new React component.',
        context: 'This project uses React with Vite and TypeScript. All components are functional.',
        steps: [
          'Place the file in `src/components/<ComponentName>.tsx`',
          'Name the file and export using PascalCase',
          'Define a TypeScript interface for props: `interface Props { ... }`',
          'Export the component as the default export',
          'Write a unit test in `tests/unit/<ComponentName>.test.tsx`',
        ],
        patterns: [
          'Functional components only — no class components',
          'Props always explicitly typed',
          'One component per file',
        ],
        antiPatterns: [
          'Do NOT use class components',
          'Do NOT use `any` in prop types',
        ],
        example: `// src/components/Button.tsx
interface Props {
  label: string;
  onClick: () => void;
}

export default function Button({ label, onClick }: Props) {
  return <button onClick={onClick}>{label}</button>;
}`,
      }),
    },
    {
      slug: 'routing',
      triggers: ['adding a route', 'new page', 'react router', 'client-side routing'],
      status: 'active',
      content: buildSkillFile({
        slug: 'routing',
        version: '1.0.0',
        framework: 'react-vite',
        category: 'routing',
        triggers: ['adding a route', 'new page', 'react router', 'client-side routing'],
        author: '@nexus-framework/skills',
        status: 'active',
        title: 'Routing (React Router)',
        whenToRead: 'Read this skill before adding any new page or route.',
        context: 'This project uses React Router for client-side routing.',
        steps: [
          'Create a page component in `src/pages/<PageName>.tsx`',
          'Add the route to `src/App.tsx` inside `<Routes>`',
          'Use `<Route path="/path" element={<PageName />} />`',
          'Use `useNavigate()` for programmatic navigation',
          'Use `useParams()` for dynamic route parameters',
        ],
        patterns: [
          'Pages in `src/pages/`, reusable components in `src/components/`',
          'Lazy-load heavy pages with `React.lazy()`',
        ],
        antiPatterns: [
          'Do NOT use `<a href>` for internal navigation — use `<Link>`',
        ],
        example: `// src/App.tsx
import { Routes, Route } from 'react-router-dom';
import HomePage from './pages/HomePage.js';
import UserPage from './pages/UserPage.js';

export default function App() {
  return (
    <Routes>
      <Route path="/" element={<HomePage />} />
      <Route path="/users/:id" element={<UserPage />} />
    </Routes>
  );
}`,
      }),
    },
    {
      slug: 'testing',
      triggers: ['writing a test', 'unit test', 'vitest', 'testing a component'],
      status: 'active',
      content: buildSkillFile({
        slug: 'testing',
        version: '1.0.0',
        framework: 'react-vite',
        category: 'testing',
        triggers: ['writing a test', 'unit test', 'vitest', 'testing a component'],
        author: '@nexus-framework/skills',
        status: 'active',
        title: 'Testing (React + Vite + Vitest)',
        whenToRead: 'Read before writing any test.',
        context: 'Vitest + Testing Library for unit and component tests.',
        steps: [
          'Create test at `tests/unit/<name>.test.tsx`',
          'Import from vitest: `describe, it, expect, vi`',
          'Use `render()` and `screen` from `@testing-library/react`',
          'Run with `yarn test`',
        ],
        patterns: ['Test public behaviour, not internals', 'One test file per source file'],
        antiPatterns: ['Do NOT test implementation details'],
        example: `import { render, screen } from '@testing-library/react';
import Button from '../../src/components/Button.js';

it('renders the label', () => {
  render(<Button label="Click me" onClick={() => {}} />);
  expect(screen.getByText('Click me')).toBeDefined();
});`,
      }),
    },
  ];
}

/* ─── SvelteKit Skills ───────────────────────────────────────── */

function getSvelteKitSkills(): SkillDefinition[] {
  return [
    {
      slug: 'component-creation',
      triggers: ['creating a Svelte component', 'new component', 'adding a .svelte file'],
      status: 'active',
      content: buildSkillFile({
        slug: 'component-creation',
        version: '1.0.0',
        framework: 'sveltekit',
        category: 'ui',
        triggers: ['creating a Svelte component', 'new component', 'adding a .svelte file'],
        author: '@nexus-framework/skills',
        status: 'active',
        title: 'Creating Components (SvelteKit)',
        whenToRead: 'Read before creating any Svelte component.',
        context: 'This project uses SvelteKit with TypeScript. Components use `.svelte` files.',
        steps: [
          'Create the file at `src/lib/components/<ComponentName>.svelte`',
          'Use `<script lang="ts">` for TypeScript',
          'Export props using `export let propName: Type`',
          'Keep styles scoped with `<style>` block',
        ],
        patterns: [
          'PascalCase file names for components',
          'Reactive declarations: `$: derivedValue = ...`',
        ],
        antiPatterns: [
          'Do NOT use `<script>` without `lang="ts"` — TypeScript is required',
        ],
        example: `<!-- src/lib/components/Card.svelte -->
<script lang="ts">
  export let title: string;
  export let body: string;
</script>

<article>
  <h2>{title}</h2>
  <p>{body}</p>
</article>

<style>
  article { border: 1px solid #ccc; padding: 1rem; }
</style>`,
      }),
    },
    {
      slug: 'routing',
      triggers: ['adding a route', 'new page', 'file-based routing', 'sveltekit route'],
      status: 'active',
      content: buildSkillFile({
        slug: 'routing',
        version: '1.0.0',
        framework: 'sveltekit',
        category: 'routing',
        triggers: ['adding a route', 'new page', 'file-based routing', 'sveltekit route'],
        author: '@nexus-framework/skills',
        status: 'active',
        title: 'Routing (SvelteKit)',
        whenToRead: 'Read before adding any new page or route.',
        context: 'SvelteKit uses file-system routing under `src/routes/`.',
        steps: [
          'Create `src/routes/<path>/+page.svelte` for a UI page',
          'Create `src/routes/<path>/+page.server.ts` for server-side data loading',
          'Use `[param]` for dynamic segments',
          'Use `+layout.svelte` for shared layout',
        ],
        patterns: [
          '`+page.svelte` renders the UI',
          '`+page.server.ts` exports a `load()` function for server data',
        ],
        antiPatterns: [
          'Do NOT manually manage routing — use the file-system convention',
        ],
        example: `// src/routes/users/[id]/+page.server.ts
export async function load({ params }) {
  const user = await getUser(params.id);
  return { user };
}

<!-- src/routes/users/[id]/+page.svelte -->
<script lang="ts">
  export let data: { user: User };
</script>
<h1>{data.user.name}</h1>`,
      }),
    },
  ];
}

/* ─── Nuxt Skills ────────────────────────────────────────────── */

function getNuxtSkills(): SkillDefinition[] {
  return [
    {
      slug: 'component-creation',
      triggers: ['creating a Vue component', 'new component', 'adding a .vue file'],
      status: 'active',
      content: buildSkillFile({
        slug: 'component-creation',
        version: '1.0.0',
        framework: 'nuxt',
        category: 'ui',
        triggers: ['creating a Vue component', 'new component', 'adding a .vue file'],
        author: '@nexus-framework/skills',
        status: 'active',
        title: 'Creating Components (Nuxt 3)',
        whenToRead: 'Read before creating any Vue component.',
        context: 'This project uses Nuxt 3 with Vue 3 Composition API and TypeScript.',
        steps: [
          'Create at `components/<ComponentName>.vue`',
          'Use `<script setup lang="ts">` (recommended Composition API style)',
          'Define props with `defineProps<{ prop: Type }>()`',
          'Define emits with `defineEmits<{ (e: "event", val: Type): void }>()`',
        ],
        patterns: [
          'Composition API with `<script setup>` — not Options API',
          'Auto-imported components — no need to import in `<script setup>`',
        ],
        antiPatterns: [
          'Do NOT use Options API (`export default { ... }`) — use `<script setup>` instead',
        ],
        example: `<!-- components/UserCard.vue -->
<script setup lang="ts">
const props = defineProps<{ name: string; email: string }>();
</script>

<template>
  <div>
    <h2>{{ props.name }}</h2>
    <p>{{ props.email }}</p>
  </div>
</template>`,
      }),
    },
    {
      slug: 'routing',
      triggers: ['adding a page', 'new route', 'nuxt routing', 'file-based routing'],
      status: 'active',
      content: buildSkillFile({
        slug: 'routing',
        version: '1.0.0',
        framework: 'nuxt',
        category: 'routing',
        triggers: ['adding a page', 'new route', 'nuxt routing', 'file-based routing'],
        author: '@nexus-framework/skills',
        status: 'active',
        title: 'Routing (Nuxt 3)',
        whenToRead: 'Read before adding any new page.',
        context: 'Nuxt 3 uses file-system routing in `pages/`.',
        steps: [
          'Create `pages/<route>.vue` for a new page',
          'Use `[param].vue` for dynamic routes',
          'Use `definePageMeta()` inside the page for route metadata',
          'Use `useFetch()` or `useAsyncData()` for data loading',
        ],
        patterns: [
          'Pages auto-registered from `pages/` directory',
          '`<NuxtLink>` for internal navigation (not `<a>`)',
        ],
        antiPatterns: [
          'Do NOT use `<a href>` for internal links — use `<NuxtLink>`',
        ],
        example: `<!-- pages/users/[id].vue -->
<script setup lang="ts">
const route = useRoute();
const { data: user } = await useFetch(\`/api/users/\${route.params.id}\`);
</script>

<template>
  <h1>{{ user?.name }}</h1>
</template>`,
      }),
    },
  ];
}

/* ─── Astro Skills ───────────────────────────────────────────── */

function getAstroSkills(): SkillDefinition[] {
  return [
    {
      slug: 'component-creation',
      triggers: ['creating an Astro component', 'new component', 'adding a .astro file'],
      status: 'active',
      content: buildSkillFile({
        slug: 'component-creation',
        version: '1.0.0',
        framework: 'astro',
        category: 'ui',
        triggers: ['creating an Astro component', 'new component', 'adding a .astro file'],
        author: '@nexus-framework/skills',
        status: 'active',
        title: 'Creating Components (Astro)',
        whenToRead: 'Read before creating any Astro component.',
        context: 'This project uses Astro. Components are `.astro` files with a component script fence (`---`).',
        steps: [
          'Create at `src/components/<ComponentName>.astro`',
          'Use frontmatter fence (`---`) for component logic',
          'Define and use Props with `Astro.props`',
          'Use TypeScript in the frontmatter: `interface Props { ... }`',
          'Add `client:load` / `client:idle` directive for interactive islands',
        ],
        patterns: [
          'Zero JS by default — add client directives only when needed',
          'Props via `const { prop } = Astro.props`',
        ],
        antiPatterns: [
          'Do NOT add client directives unless interactivity is required — Astro ships zero JS by default',
        ],
        example: `---
// src/components/Card.astro
interface Props {
  title: string;
  description: string;
}
const { title, description } = Astro.props;
---

<article>
  <h2>{title}</h2>
  <p>{description}</p>
</article>`,
      }),
    },
    {
      slug: 'routing',
      triggers: ['adding a page', 'new route', 'file-based routing', 'astro page'],
      status: 'active',
      content: buildSkillFile({
        slug: 'routing',
        version: '1.0.0',
        framework: 'astro',
        category: 'routing',
        triggers: ['adding a page', 'new route', 'file-based routing', 'astro page'],
        author: '@nexus-framework/skills',
        status: 'active',
        title: 'Routing (Astro)',
        whenToRead: 'Read before adding any new page or route.',
        context: 'Astro uses file-system routing from `src/pages/`.',
        steps: [
          'Create `src/pages/<route>.astro` for a static page',
          'Use `[param].astro` for dynamic routes',
          'Export `getStaticPaths()` for static dynamic routes',
          'Use `Astro.params` to access route parameters',
        ],
        patterns: [
          'Static by default — all pages are pre-rendered unless using SSR adapter',
          'Use `src/layouts/` for shared layout components',
        ],
        antiPatterns: [
          'Do NOT put pages outside `src/pages/` — Astro only routes from that directory',
        ],
        example: `---
// src/pages/users/[id].astro
export function getStaticPaths() {
  return [{ params: { id: '1' } }, { params: { id: '2' } }];
}
const { id } = Astro.params;
---
<h1>User {id}</h1>`,
      }),
    },
  ];
}

/* ─── Remix Skills ───────────────────────────────────────────── */

function getRemixSkills(): SkillDefinition[] {
  return [
    {
      slug: 'routing',
      triggers: ['adding a route', 'new page', 'remix route', 'loader', 'action'],
      status: 'active',
      content: buildSkillFile({
        slug: 'routing',
        version: '1.0.0',
        framework: 'remix',
        category: 'routing',
        triggers: ['adding a route', 'new page', 'remix route', 'loader', 'action'],
        author: '@nexus-framework/skills',
        status: 'active',
        title: 'Routing with Loaders & Actions (Remix)',
        whenToRead: 'Read before adding any new route, loader, or action.',
        context: 'Remix uses file-system routing under `app/routes/`. Every route file can export a `loader`, `action`, and default component.',
        steps: [
          'Create `app/routes/<route>.tsx`',
          'Export `loader` for server-side data loading: `export async function loader({ params })`',
          'Export `action` for form mutations: `export async function action({ request })`',
          'Export the default component that renders the UI',
          'Use `useLoaderData<typeof loader>()` to access loader data in the component',
          'Use `useActionData<typeof action>()` for form feedback',
          'Use `<Form method="post">` instead of `<form>` for progressive enhancement',
        ],
        patterns: [
          'Co-locate loader, action, and component in one file',
          '`<Form>` over `<form>` for Remix-aware progressive enhancement',
          'Return `json()` from loaders and actions',
        ],
        antiPatterns: [
          'Do NOT use `useEffect` to fetch data — use `loader`',
          'Do NOT use `useState` for server data — it belongs in loader',
          'Do NOT use `fetch` in components — put it in `loader` or `action`',
        ],
        example: `// app/routes/users.$id.tsx
import { json } from '@remix-run/node';
import { useLoaderData } from '@remix-run/react';

export async function loader({ params }: LoaderFunctionArgs) {
  const user = await getUser(params.id!);
  return json({ user });
}

export default function UserPage() {
  const { user } = useLoaderData<typeof loader>();
  return <h1>{user.name}</h1>;
}`,
      }),
    },
    {
      slug: 'component-creation',
      triggers: ['creating a React component', 'new component', 'adding a UI element'],
      status: 'active',
      content: buildSkillFile({
        slug: 'component-creation',
        version: '1.0.0',
        framework: 'remix',
        category: 'ui',
        triggers: ['creating a React component', 'new component', 'adding a UI element'],
        author: '@nexus-framework/skills',
        status: 'active',
        title: 'Creating Components (Remix)',
        whenToRead: 'Read before creating any new React component.',
        context: 'Remix uses React. Reusable components live in `app/components/`.',
        steps: [
          'Create at `app/components/<ComponentName>.tsx`',
          'Export as default with PascalCase name',
          'Define props interface: `interface Props { ... }`',
          'Components are client-rendered unless used only in loaders',
        ],
        patterns: ['Functional components, TypeScript strict', 'One component per file'],
        antiPatterns: ['Do NOT use class components', 'Do NOT use `any` for props'],
        example: `// app/components/UserCard.tsx
interface Props { name: string; email: string }

export default function UserCard({ name, email }: Props) {
  return <div><h2>{name}</h2><p>{email}</p></div>;
}`,
      }),
    },
  ];
}

/* ──────────────────────────────────────────────────────────────
 * Skill file builder — generates the markdown content
 * ────────────────────────────────────────────────────────────── */

interface SkillFileOptions {
  slug: string;
  version: string;
  framework: string;
  category: string;
  triggers: string[];
  author: string;
  status: 'active' | 'draft' | 'deprecated';
  title: string;
  whenToRead: string;
  context: string;
  steps: string[];
  patterns: string[];
  antiPatterns: string[];
  example: string;
  notes?: string;
}

function buildSkillFile(opts: SkillFileOptions): string {
  const triggersYaml = opts.triggers.map((t) => `  - "${t}"`).join('\n');
  const stepsList = opts.steps.map((s, i) => `${i + 1}. ${s}`).join('\n');
  const patternsList = opts.patterns.map((p) => `- ${p}`).join('\n');
  const antiPatternsList = opts.antiPatterns.map((p) => `- ${p}`).join('\n');
  const notesSection = opts.notes ? `\n## Notes\n${opts.notes}\n` : '';

  return `---
skill: ${opts.slug}
version: ${opts.version}
framework: ${opts.framework}
category: ${opts.category}
triggers:
${triggersYaml}
author: ${opts.author}
status: ${opts.status}
---

# Skill: ${opts.title}

## When to Read This
${opts.whenToRead}

## Context
${opts.context}

## Steps
${stepsList}

## Patterns We Use
${patternsList}

## Anti-Patterns — Never Do This
${antiPatternsList}

## Example
\`\`\`
${opts.example}
\`\`\`
${notesSection}`;
}

/* ──────────────────────────────────────────────────────────────
 * Helpers
 * ────────────────────────────────────────────────────────────── */

function getFrameworkLabel(framework: NexusConfig['frontendFramework']): string {
  const labels: Record<string, string> = {
    nextjs: 'Next.js',
    'react-vite': 'React + Vite',
    sveltekit: 'SvelteKit',
    nuxt: 'Nuxt 3',
    astro: 'Astro',
    remix: 'Remix',
    none: 'Framework-Agnostic',
  };
  return labels[framework] ?? framework;
}

/**
 * List all skill slugs that were generated for a given framework.
 * Used by upgrade logic to know which core skill files exist.
 */
export function getCoreSkillSlugs(framework: NexusConfig['frontendFramework']): string[] {
  const shared = getSharedSkills().map((s) => s.slug);
  const fw = getFrameworkSkills(framework).map((s) => s.slug);
  return [...fw, ...shared];
}
