/**
 * NEXUS CLI - Skills Generator
 *
 * Generates the `.nexus/skills/` directory structure for a project.
 * Skill content is sourced from the live `@nexus-framework/skills` npm package.
 *
 * What it creates:
 *   .nexus/skills/README.md          — agent-readable index of all installed skills
 *   .nexus/skills/core/<skill>.md    — framework-matched skill files (replaceable on upgrade)
 *   .nexus/skills/custom/README.md   — placeholder with instructions for user-created skills
 *
 * Ownership rules:
 *   - core/     is owned by NEXUS — regenerated on upgrade
 *   - custom/   is owned by the user — NEVER touched by NEXUS (only created once)
 *   - community/ is created empty — populated by `nexus skill install`
 */

import { getSkillContent, listSkills } from '@nexus-framework/skills';

import type { NexusConfig } from '../types/config.js';
import type { GeneratedFile } from '../types/templates.js';

/* ──────────────────────────────────────────────────────────────
 * Framework name mapping
 * CLI config uses 'nextjs'; the skills package uses 'next.js'
 * ────────────────────────────────────────────────────────────── */

const FRAMEWORK_TO_SKILLS_DIR: Record<string, string> = {
  nextjs: 'next.js',
  'react-vite': 'react-vite',
  sveltekit: 'sveltekit',
  nuxt: 'nuxt',
  astro: 'astro',
  remix: 'remix',
  none: 'shared',
};

const FRAMEWORK_LABELS: Record<string, string> = {
  nextjs: 'Next.js',
  'react-vite': 'React + Vite',
  sveltekit: 'SvelteKit',
  nuxt: 'Nuxt 3',
  astro: 'Astro',
  remix: 'Remix',
  none: 'Framework-Agnostic',
};

/* ──────────────────────────────────────────────────────────────
 * Public API
 * ────────────────────────────────────────────────────────────── */

/**
 * Generate all `.nexus/skills/` files for the project.
 * Content is read live from `@nexus-framework/skills`.
 *
 * Returns an empty array if `config.enableSkills` is explicitly false.
 * Defaults to generating skills when enableSkills is undefined (default on).
 */
export function generateSkills(config: NexusConfig): GeneratedFile[] {
  if (config.enableSkills === false) return [];

  const framework = config.frontendFramework;
  const skillsDir = FRAMEWORK_TO_SKILLS_DIR[framework] ?? 'shared';
  const files: GeneratedFile[] = [];

  // ── Framework-specific core skills ──────────────────────────
  const frameworkSlugs = listSkills(skillsDir);
  for (const slug of frameworkSlugs) {
    const content = getSkillContent(skillsDir, slug);
    if (content) {
      files.push({ path: `.nexus/skills/core/${slug}.md`, content });
    }
  }

  // ── Shared skills (always installed) ────────────────────────
  // Skip if the framework IS shared (avoids duplicates for 'none')
  if (skillsDir !== 'shared') {
    const sharedSlugs = listSkills('shared');
    for (const slug of sharedSlugs) {
      // Only add if not already provided by framework pack
      if (!frameworkSlugs.includes(slug)) {
        const content = getSkillContent('shared', slug);
        if (content) {
          files.push({ path: `.nexus/skills/core/${slug}.md`, content });
        }
      }
    }
  }

  // ── Custom skills placeholder (never overwritten) ───────────
  files.push(generateCustomReadme());

  // ── Skills README index (always regenerated) ─────────────── 
  files.push(generateSkillsReadme(framework, skillsDir));

  return files;
}

/**
 * List all skill slugs that will be generated for a given framework.
 * Used by upgrade/repair reconcile logic to know which core files exist.
 */
export function getCoreSkillSlugs(framework: NexusConfig['frontendFramework']): string[] {
  const skillsDir = FRAMEWORK_TO_SKILLS_DIR[framework] ?? 'shared';
  const frameworkSlugs = listSkills(skillsDir);

  if (skillsDir === 'shared') return frameworkSlugs;

  const sharedSlugs = listSkills('shared').filter((s) => !frameworkSlugs.includes(s));
  return [...frameworkSlugs, ...sharedSlugs];
}

/* ──────────────────────────────────────────────────────────────
 * Skills README index (.nexus/skills/README.md)
 * ────────────────────────────────────────────────────────────── */

function generateSkillsReadme(
  framework: NexusConfig['frontendFramework'],
  skillsDir: string,
): GeneratedFile {
  const frameworkLabel = FRAMEWORK_LABELS[framework] ?? framework;
  const allSlugs = getCoreSkillSlugs(framework);

  const coreRows = allSlugs
    .map((slug) => `| \`${slug}\` | [read](.nexus/skills/core/${slug}.md) |`)
    .join('\n');

  const content = `# NEXUS Skills Index

> Auto-generated by NEXUS CLI. Sourced from \`@nexus-framework/skills@0.1.0\`.
> Run \`nexus upgrade\` to refresh core skills to the latest version.
> Add your own skills in \`custom/\` using \`nexus skill new <name>\`.

---

## What Are Skills?

Skills are pre-read instruction files that tell AI agents **how to execute tasks** in this
specific project. Before performing any significant task, your AI agent checks this directory
for a matching skill and reads it fully before starting.

**Skills live in three directories:**

| Directory | Owner | Updated By |
|-----------|-------|------------|
| \`core/\` | NEXUS | Regenerated by \`nexus upgrade\` |
| \`custom/\` | You | **Never touched by NEXUS** |
| \`community/\` | Registry | \`nexus skill install <pkg>\` |

**Precedence: \`custom/\` overrides \`core/\`, which overrides \`community/\`.**

---

## Core Skills (${frameworkLabel})

> Sourced from \`@nexus-framework/skills\` — framework: \`${skillsDir}\` + \`shared\`

| Skill | File |
|-------|------|
${coreRows}

## Custom Skills

No custom skills yet. Run \`nexus skill new <name>\` to create one.

Custom skills live in \`.nexus/skills/custom/\` and are **never overwritten** by NEXUS.

## Community Skills

No community skills installed. Run \`nexus skill install <pkg>\` to install from the registry.
`;

  return { path: '.nexus/skills/README.md', content };
}

/* ──────────────────────────────────────────────────────────────
 * Custom skills placeholder
 * ────────────────────────────────────────────────────────────── */

function generateCustomReadme(): GeneratedFile {
  const content = `# Custom Skills

This directory is for **your** project-specific skills.

NEXUS will **never** read from, write to, or delete files in this directory.
It is entirely owned by you.

---

## How to Create a Custom Skill

Run:
\`\`\`
nexus skill new <name>
\`\`\`

This will scaffold a new skill file with the correct frontmatter and section structure.

## Skill File Format

Every skill must have YAML frontmatter:

\`\`\`markdown
---
skill: your-skill-slug
version: 1.0.0
framework: shared
category: ui
triggers:
  - "phrase that activates this skill"
  - "another trigger phrase"
author: your-name
status: draft
---

# Skill: Title

## When to Read This
...

## Steps
1. ...

## Patterns We Use
...

## Anti-Patterns — Never Do This
...

## Example
...
\`\`\`

## Status Values

- \`active\` — AI agents must follow this skill
- \`draft\` — Guidance only; not yet enforced
- \`deprecated\` — Outdated; flag for update

---

*Add your skills here. They take precedence over core and community skills.*
`;

  return { path: '.nexus/skills/custom/README.md', content };
}
